### PR TITLE
Add/cypress

### PR DESCRIPTION
**Pull request by gminova**
Add basic cypress tests

## 動作確認

- [x] 追加|変更した部分の影響しそうな箇所をテスト|目視確認した

### CODE REVIEW

**Review by SnoozingJellyfish — COMMENTED** [review]
Thank you for adding test! 
I would like to do the next release after doing the minimum test of the currently implemented front end. Could you give me your opinion on how much frontend testing should be done with the current app?
Although e2e testing is reliable, it's expensive and the shape of the front end may change in the future, so I don't think it's a good idea to do it too often at this point.
The concept of trophy testing seems to focus on integration testing, but what kind of testing will it be for this app? (testing with a mock backend?)
The backend (OpenFisca API) has a unit test mechanism and has been tested, so there is no need to consider it.

**Comment by gminova** [comment]
@SnoozingJellyfish currently there are 0% front end tests, Cypress is a great library to do all types of tests;

> Cypress enables you to write all types of tests:
> 
> [End-to-end tests](https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test)
> [Component tests](https://docs.cypress.io/guides/component-testing/overview)
> Integration tests
> Unit tests

This PR is just meant to add Cypress with some basic tests but not tests the whole app; It's just a start;
Cypress only tests the front end code that runs in the browser, back end logic is mocked so no burden is added to the API;
e2e tests improve code quality and reliability, and need to be updated similar to how you would update back end logic with back end tests; 

I hope this helps;

**Comment by SnoozingJellyfish** [comment]
@gminova 
Thank you for your information!
I understand that comprehensive testing is possible with cypress and this PR is just the beginning. (I'll merge the PR.)
Could you consider the front-end test policy, plan, granularity, etc. and create an issue? I think other people can contribute after you create an issue.
Later, I realized that the backend is already running locally in docker container and the processing time is short, so we may not need to mock it.
The backend is basically merged into the develop branch after testing.

We can check the behavior of the backend API in swagger.ui. (`docker compose up` and `http://localhost:8080`.)
Household json format and its specification is described on API of [Tips](https://project-inclusive.github.io/OpenFisca-Japan/about_openfisca#tips).

Please contact us if you have any questions. Video calls are also possible.

**Comment by SnoozingJellyfish** [comment]
I appreciate adding issues!

**Pull request merged**
